//export const dollDescription = 'The image shows a doctors visit. A little girl is visiting a doctor and showing him a doll. The doctor is using a stethoscope to imitate listening to the dolls heart beats. The little girl is wearing a red hat, green jacket and a patterned skirt. The doctor has graying hair and is wearing a regular black suit.';
export const dollDescription = `The image shown a doctor and a girl playing pretend. The girl has brought her sick doll to the doctor, and the doctor is pretending to listen to the dolls heartbeats using a stethoscope. The girl is standing in front of the doctor holding up the doll, while the doctor is sitting in a chair and holding the stethoscope to his ears and the dolls chest. 

The girl is wearing brown shoes, white pants, a checkerboard patterned coat, a blue shirt and a red hat. The doctor is wearing a black suit and black pants with a white undershirt. The doctor is not wearing anything on his head, and his hair is gray. Beneath the chair of the doctor is a bag, probably a doctors bag. A stack of books or documents are directly under the doctors chair. Behind the doctor is a desk containing many books. There are also two candle stakes on the desk.`
//export const runawayDescription = "The image shows a man and a boy sitting next to each other in what looks like a diner. Behind the counter of the diner stands another man. The man sitting next to the boy appears to be a police officer. He's wearing a normal blue police uniform. On the ground beside the boys chair is a small red sack attached to a stick, indicating that the boy is a runaway.";
export const runawayDescription = `The image shows a classic American diner. There are three people, a man behind the counter, and a man and a boy sitting in front of the counter. Besides the boys chair is a knapsack on a stick, suggesting that the boy has run away from home. The man sitting next to the boy is dressed like a mail man or a police officer. He is wearing a blue hat, blue uniform shirt and pants, a black belt and black shoes. He also has a small pouch around his shoulder. The boy is wearing a yellow shirt, blue pants and brown shoes. The man behind the counter looks like a cook. He is wearing white clothes. The cook is also starting to go bald. On the counter there are coffee cups and a coffee mug. Behind the cook is a blackboard where the words special today are written. The rest of the board is obscured by the cooks body.`
export const freedomDescription = 'The image shows a group of family or friends gathered together for presumably a thanksgiving dinner. There and adults and children sitting around a table and smiling. At the head of the table stands a old man wearing a black suit. Next to him is an old lady who is in the process of putting a huge turkey dinner down onto the table.';
export const breakfastDescription = "The image shows what looks like a married couple having an argument during breakfast. A man and a woman are sitting face to face at a table. They are both holding newspapers and the man is shouting at the woman, and the woman looks upset and has her arms crossed. On the floor besides the table is a young child who is crying, presumably due to his parents loud yelling. Under the woman's chair lies a black and white dog. The woman is wearing red heels and a blue dress. The man is wearing a black suit with black pants and a white under shirt. The young boy is wearing a blue t-shirt and and striped overalls. The boy is also holding a teddy bear. On the table between the two adults is a toaster currently toasting bread. They are presumably eating breakfast while arguing about politics. A stove can be seen in the edge of the picture."
export const stayDescription = 'The image contains a man, a boy and a dog. They are standing together on a hill and looking towards the ocean. Both the man and the boy are wearing blue clothes. The man is wearing a hat, but the boy is holding a hat in his hands. Above the man three seagulls are flying Below the hill the roofs of a few houses can be seen, and in the background a ship can be seen in the ocean.';
export const dateDescription = "The image shows two separate frames. One frame shows a woman getting ready in front of a mirror. The other frame shows a man getting ready in front of a mirror. It looks like they are getting ready for a date. The man is wearing a red shirt, blue pants and black shoes. He has a red handkerchief in his pocket. The woman is wearing a pink dress, but she has not put on shoes yet. In front of the man is a portrait drawing of a woman. This is presumably the woman he is going on a date with. On the woman's wall is a portrait drawing of a man. This is presumably a drawing of the man she id going on a date with. In the mans frame a bed can be seen. On this bed is a jacket and a hat. There is also a clock above the bed. In front of the man is a table with a lot of clutter on it. There are several bags and a bowl containing bottles."